### ISSUE TITLE
Error when starting streams-dynamodb and streams-es

### ISSUE THREAD

**Issue by jasonkliu** [AWS-South-Wales-User-Group/qldb-bicycle-licence#25]
Hi,

A couple errors when starting streams-dynamodb.  To fix the first error I ran `npm update`, but then ran into the second error.
To fix the second error, I ran `npm install serverless-iam-roles-per-function@next`.  Looks like it was fixed here: https://github.com/serverless/serverless/issues/8358

```
$ npm run sls -- deploy

> streams-dynmamodb@1.0.0 sls
> serverless "deploy"

Serverless: Uploading service streams-dynmamodb.zip file to S3 (1.82 MB)...
Serverless: Operation failed!
  Serverless Error ---------------------------------------

  An error occurred: DynamoDBGetLicenceLambdaFunction - Resource handler returned message: "Uploaded file must be a non-empty zip (Service: Lambda, Status Code: 400, Request ID: 59b0, Extended Request ID: null)" (RequestToken: 479e, HandlerErrorCode: InvalidRequest).
```

```
 Type Error ----------------------------------------------

  TypeError: this.awsPackagePlugin.validateStatements is not a function
      at ServerlessIamPerFunctionPlugin.validateStatements (/qldb-bicycle-licence/streams-dynmamodb/node_modules/serverless-iam-roles-per-function/dist/lib/index.js:49:31)
      at ServerlessIamPerFunctionPlugin.createRoleForFunction (/qldb-bicycle-licence/streams-dynmamodb/node_modules/serverless-iam-roles-per-function/dist/lib/index.js:189:14)
      at ServerlessIamPerFunctionPlugin.createRolesPerFunction (/qldb-bicycle-licence/streams-dynmamodb/node_modules/serverless-iam-roles-per-function/dist/lib/index.js:284:18)
      at PluginManager.runHooks (/qldb-bicycle-licence/streams-dynmamodb/node_modules/serverless/lib/classes/PluginManager.js:601:41)
/serverless-iam-roles
      at PluginManager.invoke (/qldb-bicycle-licence/streams-dynmamodb/node_modules/serverless/lib/classes/PluginManager.js:638:20)
      at async PluginManager.spawn (/qldb-bicycle-licence/streams-dynmamodb/node_modules/serverless/lib/classes/PluginManager.js:663:5)
      at async before:deploy:deploy (/qldb-bicycle-licence/streams-dynmamodb/node_modules/serverless/lib/plugins/deploy.js:65:11)
      at async PluginManager.runHooks (/qldb-bicycle-licence/streams-dynmamodb/node_modules/serverless/lib/classes/PluginManager.js:601:35)
      at async PluginManager.invoke (/qldb-bicycle-licence/streams-dynmamodb/node_modules/serverless/lib/classes/PluginManager.js:638:9)
      at async PluginManager.run (/qldb-bicycle-licence/streams-dynmamodb/node_modules/serverless/lib/classes/PluginManager.js:700:7)
      at async Serverless.run (/qldb-bicycle-licence/streams-dynmamodb/node_modules/serverless/lib/Serverless.js:468:5)
      at async /qldb-bicycle-licence/streams-dynmamodb/node_modules/serverless/scripts/serverless.js:836:9
```

**Comment by jasonkliu** [comment]
For streams-es I had the same two errors as above which were resolved with the same steps.  Then I ran into this error: 

```
 Serverless Error ----------------------------------------

  The CloudFormation template is invalid: Template error: every Fn::GetAtt object requires two non-empty parameters, the resource name and the resource attribute
```

The fix is in https://github.com/AWS-South-Wales-User-Group/qldb-bicycle-licence/pull/26
